Description



PREHOOK: query: create table t1(x int, constraint pk1 primary key (x) disable novalidate)
PREHOOK: type: CREATETABLE
PREHOOK: Output: database:default
PREHOOK: Output: default@t1
POSTHOOK: query: create table t1(x int, constraint pk1 primary key (x) disable novalidate)
POSTHOOK: type: CREATETABLE
POSTHOOK: Output: database:default
POSTHOOK: Output: default@t1
PREHOOK: query: create table t2(x int, constraint pk1 primary key (x) disable novalidate)
PREHOOK: type: CREATETABLE
PREHOOK: Output: database:default
PREHOOK: Output: default@t2
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:For direct MetaStore DB connections, we don't support retries at the client level.)


In the above case, it seems like useful error message is lost. It looks like a  generic problem with metastore server/client exception handling and message propagation. Seems like exception parsing logic of RetryingMetaStoreClient::invoke() needs to be updated.


